// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmXMpN5UpD-cRUScpKkOnLKqcK3Tasb7s',
    appId: '1:899162124801:web:c8dc823b99614fc3124600',
    messagingSenderId: '899162124801',
    projectId: 'app-alimentacion-1c03d',
    authDomain: 'app-alimentacion-1c03d.firebaseapp.com',
    databaseURL: 'https://app-alimentacion-1c03d-default-rtdb.firebaseio.com',
    storageBucket: 'app-alimentacion-1c03d.appspot.com',
    measurementId: 'G-TVY0ZVFF0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6nQ4HTQqJe-oh3kLYwQK4lqjqtgPOBgY',
    appId: '1:899162124801:android:cb6f4e05abdbb7d1124600',
    messagingSenderId: '899162124801',
    projectId: 'app-alimentacion-1c03d',
    databaseURL: 'https://app-alimentacion-1c03d-default-rtdb.firebaseio.com',
    storageBucket: 'app-alimentacion-1c03d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEnxn5ymZ2TxfIkzfq08e7eoSdIpnpH_0',
    appId: '1:899162124801:ios:61c6f7d0dcfcfe05124600',
    messagingSenderId: '899162124801',
    projectId: 'app-alimentacion-1c03d',
    databaseURL: 'https://app-alimentacion-1c03d-default-rtdb.firebaseio.com',
    storageBucket: 'app-alimentacion-1c03d.appspot.com',
    iosBundleId: 'com.example.appPlanes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmXMpN5UpD-cRUScpKkOnLKqcK3Tasb7s',
    appId: '1:899162124801:web:db0f16209c64ed23124600',
    messagingSenderId: '899162124801',
    projectId: 'app-alimentacion-1c03d',
    authDomain: 'app-alimentacion-1c03d.firebaseapp.com',
    databaseURL: 'https://app-alimentacion-1c03d-default-rtdb.firebaseio.com',
    storageBucket: 'app-alimentacion-1c03d.appspot.com',
    measurementId: 'G-4SMKRY2BT0',
  );
}
